### ISSUE TITLE
Committing changes to OSDC Repos

### ISSUE THREAD

**Issue by daemon1024** [osdc/ct-api#10]
- [ ]  Committing on OSDC repos
    - [x]  adding table row in meetups
    - [ ]  adding resources post meetup

_Originally posted by @shermix in https://github.com/osdc/ct-api/issues/1#issuecomment-589684349_

Instead of committing to the repos directly , we will be opening a PR using a github app ( similar to dependabot for updating dependencies).
I have made an potential implementation to figure out how to open a PR at https://github.com/daemon1024/gitauto

**Comment by daemon1024** [comment]
I think we can use showdownjs.com to convert the markdown to html and then use cheerio to add data to <td>

**Comment by daemon1024** [comment]
update : https://github.com/daemon1024/gitauto has the full workflow ready , just need to integrate it with the ct-api to commit to the repo on mutation :)

**Comment by sidntrivedi012** [comment]
Adding details fixed in #11 .
